sms/backend/app/project/urls.py
# SPDX-FileCopyrightText: 2020 - 2023
# - Martin Abbrent <martin.abbrent@ufz.de>
# - Kotyba Alhaj Taha <kotyba.alhaj-taha@ufz.de>
# - Wilhelm Becker <wilhelm.becker@gfz-potsdam.de>
# - Nils Brinckmann <nils.brinckmann@gfz-potsdam.de>
# - Marc Hanisch <marc.hanisch@gfz-potsdam.de>
# - Luca Johannes Nendel <luca-johannes.nendel@ufz.de>
# - Helmholtz Centre Potsdam - GFZ German Research Centre for Geosciences (GFZ, https://www.gfz-potsdam.de)
# - Helmholtz Centre for Environmental Research GmbH - UFZ (UFZ, https://www.ufz.de)
#
# SPDX-License-Identifier: HEESIL-1.0


"""Routing for the urls & the endpoints."""

from flask_rest_jsonapi import Api

from project.api.resources import *

from .api.resources.permission_group_resources import PermissionGroups

api = Api()

api.route(Ping, "test_connection", "/ping")
api.route(PermissionGroups, "permission_group_list", "/permission-groups")

# Platform
api.route(
    PlatformList,
    "platform_list",
    "/platforms",
    "/contacts/<int:contact_id>/platforms",
)
api.route(
    PlatformDetail,
    "platform_detail",
    "/platforms/<int:id>",
)

# Platform Parameter
api.route(
    PlatformParameterDetail,
    "platform_parameter_detail",
    "/platform-parameters/<int:id>",
)
api.route(
    PlatformParameterList,
    "platform_parameter_list",
    "/platform-parameters",
    "/platforms/<int:platform_id>/platform-parameters",
)
# Platform Parameter Value Change Action
api.route(
    PlatformParameterValueChangeActionDetail,
    "platform_parameter_value_change_action_detail",
    "/platform-parameter-value-change-actions/<int:id>",
)
api.route(
    PlatformParameterValueChangeActionList,
    "platform_parameter_value_change_action_list",
    "/platform-parameter-value-change-actions",
    "/platforms/<int:platform_id>/platform-parameter-value-change-actions"
)
# Platform Attachment
api.route(
    PlatformAttachmentList,
    "platform_attachment_list",
    "/platform-attachments",
    "/platforms/<int:platform_id>/platform-attachments",
)
api.route(
    PlatformAttachmentDetail,
    "platform_attachment_detail",
    "/platform-attachments/<int:id>",
)
# Platform Images
api.route(
    PlatformImageList,
    "platform_image_list",
    "/platform-images",
    "/platforms/<int:platform_id>/platform-images",
)
api.route(
    PlatformImageDetail,
    "platform_image_detail",
    "/platform-images/<int:id>"
)
# configuration Attachment
api.route(
    ConfigurationAttachmentList,
    "configuration_attachment_list",
    "/configuration-attachments",
    "/configurations/<int:configuration_id>/configuration-attachments",
)
api.route(
    ConfigurationAttachmentDetail,
    "configuration_attachment_detail",
    "/configuration-attachments/<int:id>",
)
# Configuration Images
api.route(
    ConfigurationImageList,
    "configuration_image_list",
    "/configuration-images",
    "/configurations/<int:configuration_id>/configuration-images",
)
api.route(
    ConfigurationImageDetail,
    "configuration_image_detail",
    "/configuration-images/<int:id>"
)
# site Attachment
api.route(
    SiteAttachmentList,
    "site_attachment_list",
    "/site-attachments",
    "/sites/<int:site_id>/site-attachments",
)
api.route(
    SiteAttachmentDetail,
    "site_attachment_detail",
    "/site-attachments/<int:id>",
)
# Site Images
api.route(
    SiteImageList,
    "site_image_list",
    "/site-images",
    "/sites/<int:site_id>/site-images",
)
api.route(
    SiteImageDetail,
    "site_image_detail",
    "/site-images/<int:id>"
)
# Device
api.route(
    DeviceList,
    "device_list",
    "/devices",
    "/contacts/<int:id>/devices",
)
api.route(
    DeviceDetail,
    "device_detail",
    "/devices/<int:id>",
)
# Device Property
api.route(
    DevicePropertyDetail,
    "device_property_detail",
    "/device-properties/<int:id>",
)

api.route(
    DevicePropertyList,
    "device_property_list",
    "/device-properties",
    "/devices/<int:device_id>/device-properties",
)
# Device Parameter
api.route(
    DeviceParameterDetail,
    "device_parameter_detail",
    "/device-parameters/<int:id>",
)
api.route(
    DeviceParameterList,
    "device_parameter_list",
    "/device-parameters",
    "/devices/<int:device_id>/device-parameters",
)
# Device Parameter Value Change Action
api.route(
    DeviceParameterValueChangeActionDetail,
    "device_parameter_value_change_action_detail",
    "/device-parameter-value-change-actions/<int:id>",
)
api.route(
    DeviceParameterValueChangeActionList,
    "device_parameter_value_change_action_list",
    "/device-parameter-value-change-actions",
    "/devices/<int:device_id>/device-parameter-value-change-actions"
)
# Device Attachment
api.route(
    DeviceAttachmentList,
    "device_attachment_list",
    "/device-attachments",
    "/devices/<int:device_id>/device-attachments",
)
api.route(
    DeviceAttachmentDetail,
    "device_attachment_detail",
    "/device-attachments/<int:id>",
)
# Device Images
api.route(
    DeviceImageList,
    "device_image_list",
    "/device-images",
    "/devices/<int:device_id>/device-images",
)
api.route(
    DeviceImageDetail,
    "device_image_detail",
    "/device-images/<int:id>"
)

# CustomField
api.route(
    CustomFieldList,
    "customfield_list",
    "/customfields",
    "/devices/<int:device_id>/customfields",
)
api.route(
    CustomFieldDetail,
    "customfield_detail",
    "/customfields/<int:id>",
)

# Contact
api.route(
    ContactList,
    "contact_list",
    "/contacts",
    "/devices/<int:device_id>/contacts",
    "/platforms/<int:platform_id>/contacts",
    "/configurations/<int:configuration_id>/contacts",
)
api.route(
    ContactDetail,
    "contact_detail",
    "/contacts/<int:id>",
)
api.route(
    ControllerConfigurationMountingActions,
    "controller_configuration_mounting_actions",
    "/controller/configurations/<int:configuration_id>/mounting-actions",
)
api.route(
    ControllerConfigurationMountingActionTimepoints,
    "controller_configuration_mounting_action_timepoints",
    "/controller/configurations/<int:configuration_id>/mounting-action-timepoints",
)
api.route(
    ControllerConfigurationParameterValues,
    "controller_configuration_parameter_values",
    "/controller/configurations/<int:configuration_id>/parameter-values"
)
api.route(
    ControllerDeviceParameterValues,
    "controller_device_parameter_values",
    "/controller/devices/<int:device_id>/parameter-values"
)
api.route(
    ControllerPlatformParameterValues,
    "controller_platform_parameter_values",
    "/controller/platforms/<int:platform_id>/parameter-values"
)
api.route(
    DeviceAvailabilities,
    "device_availabilities",
    "/controller/device-availabilities",
)
api.route(
    PlatformAvailabilities,
    "platform_availabilities",
    "/controller/platform-availabilities",
)
# User Info
api.route(
    UserInfo,
    "user_info",
    "/user-info",
)
# Users
api.route(
    UserList,
    "user_list",
    "/users",
    "/contacts/<int:id>/users",
)
api.route(UserDetail, "user_detail", "/users/<int:id>")
# User modifications
api.route(AcceptTermsOfUse, "accept_terms_of_use", "/accept-terms-of-use")
api.route(RevokeApikey, "revoke_apikey", "/revoke-apikey")

# Configuration
api.route(
    ConfigurationList,
    "configuration_list",
    "/configurations",
    "/sites/<int:site_id>/configurations",
)
api.route(
    ConfigurationDetail,
    "configuration_detail",
    "/configurations/<int:id>",
)
# GenericDeviceAction
api.route(
    GenericDeviceActionList,
    "generic_device_action_list",
    "/generic-device-actions",
    "/devices/<int:device_id>/generic-device-actions",
)
api.route(
    GenericDeviceActionDetail,
    "generic_device_action_detail",
    "/generic-device-actions/<int:id>",
)
# GenericDeviceActionAttachment
api.route(
    GenericDeviceActionAttachmentList,
    "generic_device_action_attachment_list",
    "/generic-device-action-attachments",
)
api.route(
    GenericDeviceActionAttachmentDetail,
    "generic_device_action_attachment_detail",
    "/generic-device-action-attachments/<int:id>",
)
# GenericPlatformAction
api.route(
    GenericPlatformActionList,
    "generic_platform_action_list",
    "/generic-platform-actions",
    "/platforms/<int:platform_id>/generic-platform-actions",
)
api.route(
    GenericPlatformActionDetail,
    "generic_platform_action_detail",
    "/generic-platform-actions/<int:id>",
)
# GenericPlatformActionAttachment
api.route(
    GenericPlatformActionAttachmentList,
    "generic_platform_action_attachment_list",
    "/generic-platform-action-attachments",
)
api.route(
    GenericPlatformActionAttachmentDetail,
    "generic_platform_action_attachment_detail",
    "/generic-platform-action-attachments/<int:id>",
)

# GenericConfigurationAction
api.route(
    GenericConfigurationActionList,
    "generic_configuration_action_list",
    "/generic-configuration-actions",
    "/configurations/<int:configuration_id>/generic-configuration-actions",
)
api.route(
    GenericConfigurationActionDetail,
    "generic_configuration_action_detail",
    "/generic-configuration-actions/<int:id>",
)
# GenericConfigurationActionAttachment
api.route(
    GenericConfigurationActionAttachmentList,
    "generic_configuration_action_attachment_list",
    "/generic-configuration-action-attachments",
)
api.route(
    GenericConfigurationActionAttachmentDetail,
    "generic_configuration_action_attachment_detail",
    "/generic-configuration-action-attachments/<int:id>",
)

# MountDeviceAction
api.route(
    DeviceMountActionList,
    "device_mount_action_list",
    "/device-mount-actions",
    "/configurations/<int:configuration_id>/device-mount-actions",
    "/devices/<int:device_id>/device-mount-actions",
    "/platforms/<int:parent_platform_id>/device-mount-actions",
)
api.route(
    DeviceMountActionDetail,
    "device_mount_action_detail",
    "/device-mount-actions/<int:id>",
)
# MountPlatformAction
api.route(
    PlatformMountActionList,
    "platform_mount_action_list",
    "/platform-mount-actions",

sms/backend/app/project/views/docs.py
# SPDX-FileCopyrightText: 2022
# - Kotyba Alhaj Taha <kotyba.alhaj-taha@ufz.de>
# - Nils Brinckmann <nils.brinckmann@gfz-potsdam.de>
# - Helmholtz Centre Potsdam - GFZ German Research Centre for Geosciences (GFZ, https://www.gfz-potsdam.de)
# - Helmholtz Centre for Environmental Research GmbH - UFZ (UFZ, https://www.ufz.de)
#
# SPDX-License-Identifier: HEESIL-1.0

"""Views for the OpenAPI specification."""

import importlib
import json
import pkgutil

from flask import Blueprint, current_app, render_template, url_for

from ..config import env
from . import openapi_parts

docs_routes = Blueprint(
    "docs", __name__, url_prefix=env("URL_PREFIX", "/rdm/svm-api/v1")
)


@docs_routes.route("/swagger", methods=["GET"])
def swagger():
    """Render the swagger UI."""
    return render_template("swaggerui.html")


@docs_routes.route("/openapi", methods=["GET"])
def openapi():
    """Render the OpenAPI UI."""
    redirect_url = url_for("docs.openapi_callback", _external=True)
    return render_template(
        "openapi.html",
        client_id=current_app.config["PKCE_CLIENT_ID"],
        scopes=current_app.config["PKCE_SCOPES"],
        redirect_url=redirect_url,
    )


@docs_routes.route("/login-callback", methods=["GET"])
def openapi_callback():
    """Provide the login callback for the OpenAPI OIDC Login mechanism."""
    return render_template("auth_pages/oauth2-redirect.html")


@docs_routes.route("/openapi.json", methods=["GET"])
def openapi_json():
    """Return the OpenAPI specification in json."""
    # We parameterize this a little bit in order to provide the docs
    # for the specific instance of the SMS.
    #
    # We reuse the url prefix here, so we fill the base url that points
    # to all the other routes as well.
    url = docs_routes.url_prefix
    description = "SMS Instance"
    backend_version = current_app.config.get("SMS_VERSION")
    servers = [
        {
            "url": url,
            "description": description,
        },
    ]
    token_endpoint = current_app.config.get("OIDC_TOKEN_ENDPOINT")
    authorization_endpoint = current_app.config.get("OIDC_AUTHORIZATION_ENDPOINT")
    term_of_use_url = (
        current_app.config.get("SMS_FRONTEND_URL", "") + "/info/terms-of-use"
    )

    paths = {}
    components = {"responses": {}, "requestBodies": {}, "parameters": {}, "schemas": {}}
    # We externalized some of the openapi specs in order to make
    # their handling a bit easier.
    # We use python files - as they allow both setting the values explicitly
    # (as in json files), and it allows us to inspect the routes
    # and schemas that we expose.
    # Compared to plain json files it allows us to use comments within
    # the files too.
    # We load them from all the submodules in the openapi_parts folder.
    for submodule in pkgutil.iter_modules(openapi_parts.__path__):
        module_name = openapi_parts.__name__ + "." + submodule.name
        module_data = importlib.import_module(module_name)

        external_file_paths = getattr(module_data, "paths", {})
        for path in external_file_paths.keys():
            paths[path] = json.dumps(external_file_paths[path])
        external_file_components = getattr(module_data, "components", {})
        for component_type in components.keys():
            single_component_data = external_file_components.get(component_type, {})
            for key in single_component_data.keys():
                components[component_type][key] = json.dumps(single_component_data[key])

    result = render_template(
        "openapi.json",
        backend_version=backend_version,
        servers=servers,
        token_endpoint=token_endpoint,
        authorization_endpoint=authorization_endpoint,
        term_of_use_url=term_of_use_url,
        paths=paths,
        response_components=components["responses"],
        request_body_components=components["requestBodies"],
        parameter_components=components["parameters"],
        schema_components=components["schemas"],
    )
    return result, 200, {"Content-type": "application/json"}

sms/backend/app/templates/openapi.html
<!-- HTML for static distribution bundle build -->
<!DOCTYPE html>
<!--
SPDX-FileCopyrightText: 2021 - 2022
- Kotyba Alhaj Taha <kotyba.alhaj-taha@ufz.de>
- Helmholtz Centre for Environmental Research GmbH - UFZ (UFZ, https://www.ufz.de)

SPDX-License-Identifier: HEESIL-1.0
-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Swagger UI</title>
    <link rel="stylesheet" type="text/css"
          href="{{ url_for('static', filename='css/swagger-ui.css') }}"/>
    <link rel="icon" type="image/png"
          href="{{ url_for('static', filename='img/favicon-32x32.png') }}" sizes="32x32"/>
    <link rel="icon" type="image/png"
          href="{{ url_for('static', filename='img/favicon-16x16.png') }}" sizes="16x16"/>
    <style>
        html {
            box-sizing: border-box;
            overflow: -moz-scrollbars-vertical;
            overflow-y: scroll;
        }

        *,
        *:before,
        *:after {
            box-sizing: inherit;
        }

        body {
            margin: 0;
            background: #fafafa;
        }
    </style>
</head>

<body>
<div id="swagger-ui"></div>

<script src="{{ url_for('static', filename='js/swagger-ui-bundle.js') }}" charset="UTF-8"></script>
<script src="{{ url_for('static', filename='js/swagger-ui-standalone-preset.js') }}"
        charset="UTF-8"></script>
<script>
    window.onload = function () {
        // Begin Swagger UI call region
        const ui = SwaggerUIBundle({
            url: "{{ url_for('docs.openapi_json') }}",
            dom_id: '#swagger-ui',
            docExpansion: 'none',
            // SET redirect url: im Backend it is /login-callback
            oauth2RedirectUrl: '{{ redirect_url }}',
            deepLinking: true,
            presets: [
                SwaggerUIBundle.presets.apis,
                SwaggerUIStandalonePreset
            ],
            plugins: [
                SwaggerUIBundle.plugins.DownloadUrl
            ],
            layout: "StandaloneLayout"
        });
        // End Swagger UI call region
        const pkceClientId = '{{ client_id }}'; // SET client id
        const pkceScopes = '{{ scopes }}'; // SET scopes

        ui.initOAuth({
            clientId: pkceClientId,
            clientSecret: null,
            scopes: pkceScopes,
            usePkceWithAuthorizationCodeGrant: true
        })
        window.ui = ui;
    };
</script>
</body>
</html>

sms/backend/app/templates/swaggerui.html
<!-- HTML for static distribution bundle build -->
<!DOCTYPE html>
<!--
SPDX-FileCopyrightText: 2021 - 2022
- Kotyba Alhaj Taha <kotyba.alhaj-taha@ufz.de>
- Helmholtz Centre for Environmental Research GmbH - UFZ (UFZ, https://www.ufz.de)

SPDX-License-Identifier: HEESIL-1.0
-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Swagger UI</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/swagger-ui.css') }}">
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='img/favicon-32x32.png') }}" sizes="32x32"/>
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='img/favicon-16x16.png') }}" sizes="16x16"/>
    <style>
        html {
            box-sizing: border-box;
            overflow: -moz-scrollbars-vertical;
            overflow-y: scroll;
        }

        *,
        *:before,
        *:after {
            box-sizing: inherit;
        }

        body {
            margin: 0;
            background: #fafafa;
        }
    </style>
</head>

<body>
<div id="swagger-ui"></div>

<script src="{{ url_for('static', filename='js/swagger-ui-bundle.js') }}"></script>
<script src="{{ url_for('static', filename='js/swagger-ui-standalone-preset.js') }}"></script>
<script src="{{ url_for('static', filename='js/swagger-initializer.js') }}"></script>
<script src="{{ url_for('static', filename='js/swagger-ui.js') }}"></script>
<script>
    window.onload = function () {
        // Begin Swagger UI call region
        const ui = SwaggerUIBundle({
            url: "{{ url_for('static', filename='swagger.json') }}",
            dom_id: '#swagger-ui',
            docExpansion: 'none',
            deepLinking: true,
            presets: [
                SwaggerUIBundle.presets.apis,
                SwaggerUIStandalonePreset
            ],
            plugins: [
                SwaggerUIBundle.plugins.DownloadUrl
            ],
            layout: "StandaloneLayout"
        });
        // End Swagger UI call region

        window.ui = ui;
    };
</script>
</body>
</html>